services:
  frontend:
    image: ensyllis/semanticats-frontend:latest
    container_name: semantic_ats_frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://192.34.61.136:8000
    depends_on:
      - backend
    networks:
      - semantic_ats_network

  backend:
    image: ensyllis/semanticats-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - semantic_ats_network

networks:
  semantic_ats_network:
    driver: bridge